### PR TITLE
Update rapids_cudf.ipynb to work with new RAPIDS-Colab installation script

### PR DESCRIPTION
**Pull request by taureandyernv**
updated installation of RAPIDS in deep learning tutorial so that it works with new colab script

Solves: https://github.com/ritchieng/deep-learning-wizard/issues/9

### CODE REVIEW

**Comment by taureandyernv** [comment]
@ritchieng we are in release for 21.10.  would you mind updating the corresponding md file?  I used up my extra time for the day :)

**Comment by ritchieng** [comment]
Probably need an even further update to this given it's Jan 2023 :)

**Comment by ritchieng** [comment]
Thank you so much for your effort @taureandyernv, it still works well in 2023. Just tested!

**Comment by ritchieng** [comment]
Though @taureandyernv, I had to refactor some code to make majority work.

And the notebook it seems for some code, there're `cffi` package version conflict errors.

https://www.deeplearningwizard.com/machine_learning/gpu/rapids_cudf/

They're mostly on the filtering API.

```
# DO NOT RUN
# TOFIX: `cffi` package version mismatch error
print(gdf.query('integers == 1'))
```

**Comment by taureandyernv** [comment]
Thanks for fixing and merging @ritchieng.  In the last year, the Colab capability had broken (no python 3.8), and was just fixed again.  #19 will fix everything you experienced  :)

**Pull request merged**
